CREATE TYPE CAR_T AS OBJECT( 
	REGISTRATION_NUMBER VARCHAR2(100),
	COLOR VARCHAR2(20),
	PRODUCTION_YEAR NUMBER(4),
	MANUFACTURER VARCHAR2(100),
	PRICE NUMBER(8)
)

CREATE TABLE CAR_SHOWROOM (
	CAR_ID NUMBER(3),
	CAR CAR_T
)

INSERT INTO CAR_SHOWROOM VALUES(1,CAR_T('ABC23','BUTTER',1976,'VEB AUTOMOBILWERK ZWICKAU',40000));
INSERT INTO CAR_SHOWROOM VALUES(2,CAR_T('ZAD999','BLACK',2021,'KIA',900000));

SELECT CS.CAR.COLOR FROM CAR_SHOWROOM CS;

UPDATE CAR_SHOWROOM CS SET CS.CAR.COLOR='WHITE' WHERE TO_CHAR(SYSDATE,'YYYY')-CS.CAR.PRODUCTION_YEAR>5;

CREATE TYPE CAR_TABLE_TYPE AS TABLE OF CAR_T

CREATE TABLE SHOWROOM_NETWORK(
	ID INT PRIMARY KEY,
	CITY VARCHAR(100),
	CAR_TABLE CAR_TABLE_TYPE
)NESTED TABLE CAR_TABLE STORE AS CAR_NESTED

INSERT INTO SHOWROOM_NETWORK VALUES(1,'MISKOLC',CAR_TABLE_TYPE(CAR_T('AAA100','GREEN',2000,'OPEL',200000),CAR_T('AAA101','BLUE',2010,'SKODA',200000)))

INSERT INTO SHOWROOM_NETWORK VALUES(2,'DEBRECEN', CAR_TABLE_TYPE( CAR_T('AAA200','GREEN',1999,'OPEL',405670)))

SELECT * FROM TABLE(SELECT SN.CAR_TABLE FROM SHOWROOM_NETWORK SN WHERE SN.CITY='MISKOLC')

SELECT * FROM CAR_NESTED

DECLARE
	car CAR_O;
BEGIN
	CAR := CAR_O('AAA111','zöld',2010,'opel',2000000,450);
	CAR_O.WRITE_OBJECT_NAME_STRING();
	CAR.WRITE_OUT_WHEEL_NUMBER();
	CAR.WRITE_OUT_POWER();
	DBMS_OUTPUT.PUT_LINE('KOR: ' || CAR.GET_AGE());
	DBMS_OUTPUT.PUT_LINE('POWER BY WHEEL: ' ||
	CAR.POWER_BY_WHEEL(10));
	CAR.SET_POWER(10);
	DBMS_OUTPUT.PUT_LINE('POWER: ' || CAR.GET_POWER());
END;